# 依赖库的来源地址
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# 说明平台是ios，版本是9.0
platform :ios, '9.0'

# 忽略引入库的所有警告
inhibit_all_warnings!

# 针对指定target引入第三方库
target 'IOSProjectFramework' do 
    pod 'AFNetworking', '3.2.1' 
end